// Barrel re-export — keeps all existing `import { ... } from '…/db/index.js'` working.
export { closeDb, findDbPath, openDb, openReadonlyOrFail, openRepo } from './connection.js';
export { getBuildMeta, initSchema, MIGRATIONS, setBuildMeta } from './migrations.js';
export {
  fanInJoinSQL,
  fanOutJoinSQL,
  kindInClause,
  NodeQuery,
  testFilterSQL,
} from './query-builder.js';
export {
  bulkNodeIdsByFile,
  countCrossFileCallers,
  countEdges,
  countFiles,
  countNodes,
  deleteCfgForNode,
  findAllIncomingEdges,
  findAllOutgoingEdges,
  findCalleeNames,
  findCallees,
  findCallerNames,
  findCallers,
  findCrossFileCallTargets,
  findDistinctCallers,
  findFileNodes,
  findImportDependents,
  findImportSources,
  findImportTargets,
  findIntraFileCallEdges,
  findNodeById,
  findNodeByQualifiedName,
  findNodeChildren,
  findNodesByFile,
  findNodesByScope,
  findNodesForTriage,
  findNodesWithFanIn,
  getCallableNodes,
  getCallEdges,
  getCfgBlocks,
  getCfgEdges,
  getClassHierarchy,
  getCoChangeMeta,
  getComplexityForNode,
  getEmbeddingCount,
  getEmbeddingMeta,
  getFileNodesAll,
  getFunctionNodeId,
  getImportEdges,
  getNodeId,
  hasCfgTables,
  hasCoChanges,
  hasDataflowTable,
  hasEmbeddings,
  InMemoryRepository,
  iterateFunctionNodes,
  listFunctionNodes,
  purgeFileData,
  purgeFilesData,
  Repository,
  SqliteRepository,
  upsertCoChangeMeta,
} from './repository/index.js';
